tap "common-fate/granted"
tap "hashicorp/tap"
brew "act"
brew "awscli"
brew "dbmate"
brew "driftctl"
brew "fish"
brew "gh"
brew "git"
brew "go-task"
brew "golangci-lint"
brew "kubernetes-cli"
brew "mise"
brew "mockery"
brew "ollama", restart_service: :changed
brew "poppler"
brew "postgresql@17", restart_service: :changed
brew "redis", restart_service: :changed
brew "repomix"
brew "shellcheck"
brew "tfsec"
brew "tlrc"
brew "tree"
brew "uv"
brew "wget"
brew "common-fate/granted/granted"
brew "hashicorp/tap/terraform"
