brew "asdf"
brew "atlas"
brew "awscli"
brew "common-fate/granted/granted"
brew "driftctl"
brew "fish"
brew "gh"
brew "git"
brew "go-task"
brew "golangci-lint"
brew "kubernetes-cli"
brew "mockery"
brew "postgresql", restart_service: true
brew "redis", restart_service: true
brew "shellcheck"
brew "terraform"
brew "tfsec"
brew "tlrc"
brew "wget"

cask "google-cloud-sdk"
